# Generated by Django 3.2.8 on 2022-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='genre',
        ),
        migrations.AddField(
            model_name='dvd',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='theTopic', to='app.Topic'),
        ),
    ]
