# Generated by Django 3.2.8 on 2022-02-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220221_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='genre',
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theMovie', to='app.dvd')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theGenre', to='app.topic')),
            ],
        ),
    ]
